from sdk.v0 import (
    AllowedOverlap,
    ArticulatedObject,
    Articulation,
    ArticulationType,
    Box,
    CadQueryMeshExport,
    Cylinder,
    Inertia,
    Inertial,
    Material,
    Mesh,
    Mimic,
    MotionLimits,
    MotionProperties,
    Origin,
    Part,
    SDKError,
    Sphere,
    SurfaceFrame,
    SurfaceWrapMapping,
    TestContext,
    TestFailure,
    TestReport,
    ValidationError,
    Visual,
    align_centers,
    cadquery_local_aabb,
    export_cadquery_components,
    export_cadquery_mesh,
    mesh_components_from_cadquery,
    mesh_from_cadquery,
    mesh_from_input,
    part_local_aabb,
    place_on_face,
    place_on_face_uv,
    place_on_surface,
    proud_for_flush_mount,
    surface_frame,
    tessellate_cadquery,
    wrap_mesh_onto_surface,
    wrap_profile_onto_surface,
)
from sdk.v0 import __getattr__ as _sdk_v0_getattr

Link = Part
Joint = Articulation
JointType = ArticulationType
Limit = MotionLimits
Dynamics = MotionProperties

__all__ = [
    "SDKError",
    "ValidationError",
    "Link",
    "Joint",
    "JointType",
    "Limit",
    "Dynamics",
    "CadQueryMeshExport",
    "cadquery_local_aabb",
    "export_cadquery_components",
    "export_cadquery_mesh",
    "mesh_components_from_cadquery",
    "mesh_from_input",
    "tessellate_cadquery",
    "mesh_from_cadquery",
    "ArticulatedObject",
    "AllowedOverlap",
    "TestContext",
    "TestFailure",
    "TestReport",
    "SurfaceFrame",
    "SurfaceWrapMapping",
    "align_centers",
    "part_local_aabb",
    "place_on_face",
    "place_on_face_uv",
    "place_on_surface",
    "proud_for_flush_mount",
    "surface_frame",
    "wrap_profile_onto_surface",
    "wrap_mesh_onto_surface",
    "GearBase",
    "SpurGear",
    "HerringboneGear",
    "RingGear",
    "HerringboneRingGear",
    "PlanetaryGearset",
    "HerringbonePlanetaryGearset",
    "BevelGear",
    "BevelGearPair",
    "RackGear",
    "HerringboneRackGear",
    "Worm",
    "CrossedHelicalGear",
    "CrossedGearPair",
    "HyperbolicGear",
    "HyperbolicGearPair",
    "gear",
    "addGear",
    "Box",
    "Cylinder",
    "MotionProperties",
    "Mimic",
    "Inertia",
    "Inertial",
    "Articulation",
    "ArticulationType",
    "MotionLimits",
    "Material",
    "Mesh",
    "Origin",
    "Part",
    "Sphere",
    "Visual",
]


def __getattr__(name: str):
    return _sdk_v0_getattr(name)


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
