from .v0 import (
    ArticulatedObject,
    Articulation,
    ArticulationType,
    AssetContext,
    Box,
    CadQueryMeshExport,
    CollisionGenerationSettings,
    Cylinder,
    GeometryOverlap,
    Inertia,
    Inertial,
    Material,
    Mesh,
    MotionLimits,
    MotionProperties,
    Origin,
    Part,
    SDKError,
    Sphere,
    SurfaceFrame,
    SurfaceWrapMapping,
    TestContext,
    TestFailure,
    TestReport,
    UnsupportedPartFinding,
    ValidationError,
    Visual,
    align_centers_xy,
    cadquery_local_aabb,
    collision_generation_settings_from_env,
    default_contact_tol_from_env,
    default_overlap_tol_from_env,
    default_overlap_volume_tol_from_env,
    export_cadquery_components,
    export_cadquery_mesh,
    find_geometry_overlaps,
    find_unsupported_parts,
    mesh_components_from_cadquery,
    mesh_from_cadquery,
    part_local_aabb,
    place_in_front_of,
    place_on_face,
    place_on_face_uv,
    place_on_surface,
    place_on_top,
    proud_for_flush_mount,
    save_cadquery_obj,
    surface_frame,
    tessellate_cadquery,
    validate_no_geometry_overlaps,
    wrap_mesh_onto_surface,
    wrap_profile_onto_surface,
)

_GEAR_EXPORTS = {
    "GearBase",
    "SpurGear",
    "HerringboneGear",
    "RingGear",
    "HerringboneRingGear",
    "PlanetaryGearset",
    "HerringbonePlanetaryGearset",
    "BevelGear",
    "BevelGearPair",
    "RackGear",
    "HerringboneRackGear",
    "Worm",
    "CrossedHelicalGear",
    "CrossedGearPair",
    "HyperbolicGear",
    "HyperbolicGearPair",
    "gear",
    "addGear",
}

Link = Part
Joint = Articulation
JointType = ArticulationType
Limit = MotionLimits
Dynamics = MotionProperties

__all__ = [
    "SDKError",
    "ValidationError",
    "Link",
    "Joint",
    "JointType",
    "Limit",
    "Dynamics",
    "AssetContext",
    "ArticulatedObject",
    "Part",
    "Articulation",
    "ArticulationType",
    "Origin",
    "Visual",
    "Material",
    "MotionLimits",
    "MotionProperties",
    "Inertial",
    "Inertia",
    "Box",
    "Cylinder",
    "Sphere",
    "Mesh",
    "CadQueryMeshExport",
    "cadquery_local_aabb",
    "export_cadquery_components",
    "export_cadquery_mesh",
    "mesh_components_from_cadquery",
    "tessellate_cadquery",
    "save_cadquery_obj",
    "mesh_from_cadquery",
    "GeometryOverlap",
    "UnsupportedPartFinding",
    "default_contact_tol_from_env",
    "default_overlap_tol_from_env",
    "default_overlap_volume_tol_from_env",
    "find_geometry_overlaps",
    "find_unsupported_parts",
    "validate_no_geometry_overlaps",
    "CollisionGenerationSettings",
    "collision_generation_settings_from_env",
    "TestContext",
    "TestFailure",
    "TestReport",
    "SurfaceFrame",
    "SurfaceWrapMapping",
    "align_centers_xy",
    "part_local_aabb",
    "place_in_front_of",
    "place_on_face",
    "place_on_face_uv",
    "place_on_surface",
    "place_on_top",
    "proud_for_flush_mount",
    "surface_frame",
    "wrap_profile_onto_surface",
    "wrap_mesh_onto_surface",
    "GearBase",
    "SpurGear",
    "HerringboneGear",
    "RingGear",
    "HerringboneRingGear",
    "PlanetaryGearset",
    "HerringbonePlanetaryGearset",
    "BevelGear",
    "BevelGearPair",
    "RackGear",
    "HerringboneRackGear",
    "Worm",
    "CrossedHelicalGear",
    "CrossedGearPair",
    "HyperbolicGear",
    "HyperbolicGearPair",
    "gear",
    "addGear",
]


def __getattr__(name: str):
    if name in _GEAR_EXPORTS:
        from . import v0 as _v0

        value = getattr(_v0, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
