"""Prompt resources and loading helpers."""

from .loader import (
    DESIGNER_PROMPT_NAME,
    GEMINI_DESIGNER_PROMPT_NAME,
    GENERATED_PROMPTS_DIR,
    LEGACY_DESIGNER_PROMPT_NAME,
    OPENAI_DESIGNER_PROMPT_NAME,
    PROMPTING_ROOT,
    PROMPTS_ROOT,
    SECTIONS_DIR,
    SUPPORTED_SDK_DOCS_MODES,
    PromptFiles,
    load_prompt_section_text,
    load_sdk_docs_reference,
    load_system_prompt_text,
    normalize_sdk_docs_mode,
    normalize_sdk_package,
    provider_system_prompt_suffix,
    resolve_sdk_package_flags,
    resolve_system_prompt_path,
)

__all__ = [
    "GENERATED_PROMPTS_DIR",
    "LEGACY_DESIGNER_PROMPT_NAME",
    "PROMPTS_ROOT",
    "PromptFiles",
    "PROMPTING_ROOT",
    "DESIGNER_PROMPT_NAME",
    "OPENAI_DESIGNER_PROMPT_NAME",
    "GEMINI_DESIGNER_PROMPT_NAME",
    "SECTIONS_DIR",
    "SUPPORTED_SDK_DOCS_MODES",
    "load_prompt_section_text",
    "normalize_sdk_docs_mode",
    "normalize_sdk_package",
    "resolve_sdk_package_flags",
    "load_sdk_docs_reference",
    "resolve_system_prompt_path",
    "load_system_prompt_text",
    "provider_system_prompt_suffix",
]
