from .v0 import (
    ArcPipeGeometry,
    ArticulatedObject,
    Articulation,
    ArticulationType,
    Box,
    BoxGeometry,
    BufferGeometry,
    CapsuleGeometry,
    ConeGeometry,
    Cylinder,
    CylinderGeometry,
    DomeGeometry,
    ExtrudeGeometry,
    ExtrudeWithHolesGeometry,
    Inertia,
    Inertial,
    LatheGeometry,
    LoftGeometry,
    LoftSection,
    LoftTessellation,
    LouverPanelGeometry,
    Material,
    Mesh,
    MeshGeometry,
    MotionLimits,
    MotionProperties,
    Origin,
    Part,
    PipeGeometry,
    SDKError,
    SectionLoftSpec,
    ShellPartitionRegion,
    ShellPartitionSpec,
    Sphere,
    SphereGeometry,
    SurfaceFrame,
    SurfaceWrapMapping,
    SweepGeometry,
    TestContext,
    TestFailure,
    TestReport,
    TorusGeometry,
    ValidationError,
    Visual,
    WirePath,
    WirePolylineGeometry,
    align_centers,
    boolean_difference,
    boolean_intersection,
    boolean_union,
    cut_opening_on_face,
    mesh_from_geometry,
    mesh_from_input,
    part_local_aabb,
    partition_shell,
    place_on_face,
    place_on_face_uv,
    place_on_surface,
    proud_for_flush_mount,
    repair_loft,
    resample_side_sections,
    rounded_rect_profile,
    sample_arc_3d,
    sample_catmull_rom_spline_2d,
    sample_catmull_rom_spline_3d,
    sample_cubic_bezier_spline_2d,
    sample_cubic_bezier_spline_3d,
    scale_geometry_to_size,
    section_loft,
    split_superellipse_side_loft,
    superellipse_profile,
    superellipse_side_loft,
    surface_frame,
    sweep_profile_along_spline,
    tube_from_spline_points,
    wire_from_points,
    wrap_mesh_onto_surface,
    wrap_profile_onto_surface,
)

__all__ = [
    "SDKError",
    "ValidationError",
    "ArticulatedObject",
    "Part",
    "Articulation",
    "ArticulationType",
    "Origin",
    "Visual",
    "Material",
    "MotionLimits",
    "MotionProperties",
    "Inertial",
    "Inertia",
    "Box",
    "BoxGeometry",
    "CapsuleGeometry",
    "BufferGeometry",
    "Cylinder",
    "CylinderGeometry",
    "ConeGeometry",
    "DomeGeometry",
    "Sphere",
    "SphereGeometry",
    "Mesh",
    "MeshGeometry",
    "WirePath",
    "ExtrudeGeometry",
    "ExtrudeWithHolesGeometry",
    "LoftGeometry",
    "SweepGeometry",
    "PipeGeometry",
    "ArcPipeGeometry",
    "WirePolylineGeometry",
    "LatheGeometry",
    "TorusGeometry",
    "LouverPanelGeometry",
    "cut_opening_on_face",
    "boolean_union",
    "boolean_difference",
    "boolean_intersection",
    "wire_from_points",
    "tube_from_spline_points",
    "sweep_profile_along_spline",
    "mesh_from_geometry",
    "mesh_from_input",
    "LoftSection",
    "LoftTessellation",
    "SectionLoftSpec",
    "section_loft",
    "repair_loft",
    "ShellPartitionRegion",
    "ShellPartitionSpec",
    "partition_shell",
    "sample_cubic_bezier_spline_2d",
    "sample_cubic_bezier_spline_3d",
    "sample_catmull_rom_spline_2d",
    "sample_catmull_rom_spline_3d",
    "sample_arc_3d",
    "superellipse_side_loft",
    "split_superellipse_side_loft",
    "resample_side_sections",
    "rounded_rect_profile",
    "superellipse_profile",
    "scale_geometry_to_size",
    "TestContext",
    "TestFailure",
    "TestReport",
    "align_centers",
    "SurfaceFrame",
    "SurfaceWrapMapping",
    "part_local_aabb",
    "place_on_face",
    "place_on_face_uv",
    "place_on_surface",
    "proud_for_flush_mount",
    "surface_frame",
    "wrap_profile_onto_surface",
    "wrap_mesh_onto_surface",
]


def __getattr__(name: str):
    if name == "AssetContext":
        from . import v0 as _v0

        value = getattr(_v0, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
